name: expentack
description: "An expense tracker."

publish_to: 'none'  # Prevents accidental publishing to pub.dev

version: 1.0.0+1  # Application version and build number

environment:
  sdk: ^3.5.1  # Specifies the Dart SDK version

dependencies:
  flutter:
    sdk: flutter  # Core Flutter SDK
  intl: ^0.19.0  # For internationalization and localization
  fl_chart: ^0.69.0  # Charting library
  http: ^0.13.6  # For making HTTP requests
  flutter_launcher_icons: "^0.14.1"  # For changing the app icon
  cupertino_icons: ^1.0.8  # iOS-style icons
#  image: 2.0.7
  table_calendar: ^3.1.2

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icons/leaf.png"

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icons/owl_2.png"
  image_path_ios: "assets/icons/owl_2.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icons/owl_2.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/owl_2.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icons/owl_2.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter  # For running Flutter unit tests
  flutter_lints: ^4.0.0  # Recommended linting rules for good coding practices

flutter:
  uses-material-design: true  # Enables material design icons

  # assets like flower for calendar_screen
  assets:
    - assets/daily_flowers/flower_monday.png
    - assets/daily_flowers/flower_tuesday.png
    - assets/daily_flowers/flower_wednesday.png
    - assets/daily_flowers/flower_thursday.png
    - assets/daily_flowers/flower_friday.png
    - assets/daily_flowers/flower_saturday.png
    - assets/daily_flowers/flower_sunday.png

  # To add custom fonts, uncomment the following:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf